### PR TITLE
add simple Docker image for testing

### PR DESCRIPTION
**Pull request by ImreSamu**
simple Docker based testing ..

```bash
# run a simple local test matrix - with Docker
./local_test.sh
```

### CODE REVIEW

**Comment by ImreSamu** [comment]
Exepcted Log
```log
$ ./local_test.sh 

Sending build context to Docker daemon  323.1kB
Step 1/21 : ARG BASE_IMAGE_VERSION=postgres:13
Step 2/21 : FROM $BASE_IMAGE_VERSION
13: Pulling from library/postgres
Digest: sha256:117c3ea384ce21421541515edfb11f2997b2c853d4fdd58a455b77664c1adc20
Status: Image is up to date for postgres:13
 ---> 293e4ed402ba
Step 3/21 : ENV LANG=C.UTF-8     LC_ALL=C.UTF-8
 ---> Using cache
 ---> 64cd82cc591b
Step 4/21 : RUN    apt-get update     && apt-get install -y --no-install-recommends         build-essential         ca-certificates         cmake         git         postgresql-${PG_MAJOR}-pgtap         postgresql-server-dev-$PG_MAJOR         wget     && apt-get clean -y     && rm -rf /var/lib/apt/lists/* /tmp/*
 ---> Using cache
 ---> 2508ccb862ea
Step 5/21 : ARG JULIA_MAJOR=1.6
 ---> Using cache
 ---> 9e4f495732e4
Step 6/21 : ARG JULIA_VERSION=1.6.1
 ---> Using cache
 ---> 3631ff635bf1
Step 7/21 : ARG JULIA_SHA256=7c888adec3ea42afbfed2ce756ce1164a570d50fa7506c3f2e1e2cbc49d52506
 ---> Using cache
 ---> 606a376f3a5b
Step 8/21 : ENV JULIA_MAJOR=$JULIA_MAJOR
 ---> Using cache
 ---> 8ee4be7182a8
Step 9/21 : ENV JULIA_VERSION=$JULIA_VERSION
 ---> Using cache
 ---> b9bb93ba28a4
Step 10/21 : ENV JULIA_SHA256=$JULIA_SHA256
 ---> Using cache
 ---> 1aaede5e3e89
Step 11/21 : ENV JULIA_DIR=/usr/local/julia
 ---> Using cache
 ---> 84e41d9f1e57
Step 12/21 : ENV JULIA_PATH=${JULIA_DIR}
 ---> Using cache
 ---> 83d00a0ba5b7
Step 13/21 : RUN mkdir ${JULIA_DIR} &&     cd /tmp &&     wget -q https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_MAJOR}/julia-${JULIA_VERSION}-linux-x86_64.tar.gz &&     echo "$JULIA_SHA256 julia-${JULIA_VERSION}-linux-x86_64.tar.gz" | sha256sum -c - &&     tar xzf julia-${JULIA_VERSION}-linux-x86_64.tar.gz -C ${JULIA_DIR} --strip-components=1 &&     rm /tmp/julia-${JULIA_VERSION}-linux-x86_64.tar.gz
 ---> Using cache
 ---> e69ec9bd7e9d
Step 14/21 : RUN ln -fs ${JULIA_DIR}/bin/julia /usr/local/bin/julia
 ---> Using cache
 ---> 1661e2b01df5
Step 15/21 : ADD .   /pljulia
 ---> 7838bd6f53e8
Step 16/21 : WORKDIR /pljulia
 ---> Running in 3cc121fb1b12
Removing intermediate container 3cc121fb1b12
 ---> aff964cc2eea
Step 17/21 : ENV USE_PGXS=1
 ---> Running in be68f6d51564
Removing intermediate container be68f6d51564
 ---> 36670d93d29e
Step 18/21 : RUN make clean
 ---> Running in 5957b41787fe
rm -f pljulia.so pljulia.o  \
    pljulia.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
Removing intermediate container 5957b41787fe
 ---> b109195caff1
Step 19/21 : RUN make -j$(nproc)
 ---> Running in 33871080f91b
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -std=gnu99 -I'/usr/local/julia/include/julia' -fPIC -std=gnu99 -I'/usr/local/julia/include/julia' -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pljulia.o pljulia.c
/usr/bin/clang-7 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -std=gnu99 -I'/usr/local/julia/include/julia' -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o pljulia.bc pljulia.c
In file included from /usr/local/julia/include/julia/julia.h:94,
                 from pljulia.c:21:
/usr/local/julia/include/julia/julia_threads.h: In function ‘jl_gc_state_set’:
/usr/local/julia/include/julia/julia_threads.h:295:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         size_t safepoint_load = *ptls->safepoint;       \
         ^~~~~~
/usr/local/julia/include/julia/julia_threads.h:313:9: note: in expansion of macro ‘jl_gc_safepoint_’
         jl_gc_safepoint_(ptls);
         ^~~~~~~~~~~~~~~~
In file included from pljulia.c:21:
/usr/local/julia/include/julia/julia.h: In function ‘jl_gc_multi_wb’:
/usr/local/julia/include/julia/julia.h:852:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     jl_datatype_t *dt = (jl_datatype_t*)jl_typeof(ptr);
     ^~~~~~~~~~~~~
In file included from pljulia.c:21:
/usr/local/julia/include/julia/julia.h: In function ‘jl_ptr_offset’:
/usr/local/julia/include/julia/julia.h:1083:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     const void *ptrs = jl_dt_layout_ptrs(ly);
     ^~~~~
/usr/local/julia/include/julia/julia.h: In function ‘jl_is_array_zeroinit’:
/usr/local/julia/include/julia/julia.h:1257:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     jl_value_t *elty = jl_tparam0(jl_typeof(a));
     ^~~~~~~~~~
In file included from /usr/local/julia/include/julia/julia.h:94,
                 from pljulia.c:21:
/usr/local/julia/include/julia/locks.h: In function ‘jl_mutex_wait’:
/usr/local/julia/include/julia/julia_threads.h:295:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         size_t safepoint_load = *ptls->safepoint;       \
         ^~~~~~
/usr/local/julia/include/julia/locks.h:37:13: note: in expansion of macro ‘jl_gc_safepoint_’
             jl_gc_safepoint_(ptls);
             ^~~~~~~~~~~~~~~~
/usr/local/julia/include/julia/locks.h: In function ‘jl_mutex_unlock’:
/usr/local/julia/include/julia/julia_threads.h:301:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
         size_t safepoint_load = ptls->safepoint[-1];    \
         ^~~~~~
/usr/local/julia/include/julia/locks.h:81:13: note: in expansion of macro ‘jl_sigint_safepoint’
             jl_sigint_safepoint(jl_get_ptls_states());          \
             ^~~~~~~~~~~~~~~~~~~
/usr/local/julia/include/julia/locks.h:134:5: note: in expansion of macro ‘JL_SIGATOMIC_END’
     JL_SIGATOMIC_END();
     ^~~~~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -std=gnu99 -I'/usr/local/julia/include/julia' -fPIC pljulia.o -L'/usr/local/julia/lib' -Wl,--export-dynamic -Wl,-rpath,'/usr/local/julia/lib' -Wl,-rpath,'/usr/local/julia/lib/julia' -ljulia -L/usr/lib/x86_64-linux-gnu -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-7/lib  -Wl,--as-needed  -shared -o pljulia.so
Removing intermediate container 33871080f91b
 ---> 2868d9f84591
Step 20/21 : RUN make install
 ---> Running in cd1bf7b00fea
/bin/mkdir -p '/usr/share/postgresql/13/extension'
/bin/mkdir -p '/usr/share/postgresql/13/extension'
/bin/mkdir -p '/usr/lib/postgresql/13/lib'
/usr/bin/install -c -m 644 .//pljulia.control '/usr/share/postgresql/13/extension/'
/usr/bin/install -c -m 644 .//pljulia.control .//pljulia--0.8.sql  '/usr/share/postgresql/13/extension/'
/usr/bin/install -c -m 755  pljulia.so '/usr/lib/postgresql/13/lib/'
/bin/mkdir -p '/usr/lib/postgresql/13/lib/bitcode/pljulia'
/bin/mkdir -p '/usr/lib/postgresql/13/lib/bitcode'/pljulia/
/usr/bin/install -c -m 644 pljulia.bc '/usr/lib/postgresql/13/lib/bitcode'/pljulia/./
cd '/usr/lib/postgresql/13/lib/bitcode' && /usr/lib/llvm-7/bin/llvm-lto -thinlto -thinlto-action=thinlink -o pljulia.index.bc pljulia/pljulia.bc
Removing intermediate container cd1bf7b00fea
 ---> 88f1516401d7
Step 21/21 : RUN mkdir /tempdb     && chown -R postgres:postgres /tempdb     && su postgres -c 'pg_ctl -D /tempdb init'     && su postgres -c 'pg_ctl -D /tempdb start'     && make installcheck PGUSER=postgres     && su postgres -c 'pg_ctl -D /tempdb --mode=immediate stop'     && rm -rf /tempdb
 ---> Running in 8bc666d385d4
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /tempdb ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    /usr/lib/postgresql/13/bin/pg_ctl -D /tempdb -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2021-05-27 01:08:04.916 UTC [31] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-05-27 01:08:04.916 UTC [31] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-05-27 01:08:04.916 UTC [31] LOG:  listening on IPv6 address "::", port 5432
2021-05-27 01:08:04.918 UTC [31] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-05-27 01:08:04.921 UTC [32] LOG:  database system was shut down at 2021-05-27 01:08:04 UTC
2021-05-27 01:08:04.926 UTC [31] LOG:  database system is ready to accept connections
 done
server started
/usr/lib/postgresql/13/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/13/bin'    --dbname=contrib_regression create in_array_integer return_bigint return_char return_decimal return_double_precision return_integer return_numeric return_real return_smallint return_text return_varchar
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
NOTICE:  database "contrib_regression" does not exist, skipping
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test create                       ... ok           65 ms
test in_array_integer             ... ok          198 ms
test return_bigint                ... ok          191 ms
test return_char                  ... ok          197 ms
test return_decimal               ... ok          206 ms
test return_double_precision      ... ok          206 ms
test return_integer               ... ok          201 ms
test return_numeric               ... ok          216 ms
test return_real                  ... ok          207 ms
test return_smallint              ... ok          201 ms
test return_text                  ... ok          201 ms
test return_varchar               ... ok          214 ms

======================
 All 12 tests passed. 
======================

waiting for server to shut down....2021-05-27 01:08:10.251 UTC [31] LOG:  received immediate shutdown request
2021-05-27 01:08:10.252 UTC [36] WARNING:  terminating connection because of crash of another server process
2021-05-27 01:08:10.252 UTC [36] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-05-27 01:08:10.252 UTC [36] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-05-27 01:08:10.255 UTC [31] LOG:  database system is shut down
 done
server stopped
Removing intermediate container 8bc666d385d4
 ---> 175e5443114e
Successfully built 175e5443114e
Successfully tagged pljulia:pg13-jl1.6
```

**Comment by markwkm** [comment]
Thanks for putting this together!  My Docker experience is pretty light so my following questions might be more educational for myself.

I'm wondering if it would be cleaner, from the perspective of organizing files, to put all of these files under a `docker/` directory.

Instead of using `ADD` to copy the files, I'm wondering if it would be better to map the local directory.  It looks like `docker build` doesn't support mapping a path from the host, so it seems like that would require breaking things up to prepare a Docker image, build and install the extension, and run the regression tests.

I'll make time to experiment, but I thought I should ask at the same time to see what your experience has been with other projects that use Docker like this.

**Comment by ImreSamu** [comment]
> I'm wondering if it would be cleaner, from the perspective of organizing files, to put all of these files under a `docker/` directory.

like in this repo?   https://gitlab.com/dalibo/postgresql_faker/-/tree/master
* just move the Dockerfile to docker/Dockerfile 
* and add some Makefile trick. 

other - pg + Dockerfile examples 
* https://github.com/apache/datasketches-postgresql
* https://github.com/ankane/pgvector

> Instead of using ADD to copy the files,

I don't know any better method  -  for a 2in1 solution   ( Testing + creating  a final Docker image )

the other method is a 2 separated steps
* building  with "building images"  and in this case we can use "volume" ..   and creating a  .deb package 
* and in the second step - we build the final docker image - for publishing.

For the "building image" - example:   https://github.com/postgis/postgis-build-env
*  used with: https://github.com/postgis/postgis/blob/master/.github/workflows/ci.yml )

As I see - we can add a similar chown lines 
*   `ADD --chown=postgres:postgres . /src/postgis`

**Comment by markwkm** [comment]
Thanks for the pointers.  I'll play with it a little more and learn what I can.  Will get back to you soon.

**Comment by markwkm** [comment]
I have some ideas for some more extensive changes, but I'll share them at a later time (outside of this pull request) to see if they are good ideas.

I'm wondering if this minor filename change and move looks ok for this pull request?

```patch
From af2fa39746eb66bb323a480fb0c400b4be85ed81 Mon Sep 17 00:00:00 2001
From: Mark Wong <markwkm@gmail.com>
Date: Fri, 28 May 2021 18:38:17 +0000
Subject: [PATCH] Move docker related shell scripts to its own dir

---
 local_test.sh => docker/build | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)
 rename local_test.sh => docker/build (83%)

diff --git a/local_test.sh b/docker/build
similarity index 83%
rename from local_test.sh
rename to docker/build
index 1ce4cbf..fe66901 100755
--- a/local_test.sh
+++ b/docker/build
@@ -3,6 +3,8 @@ set -o errexit

 # simple test matrix - for local testing

+DOCKER_DIR=`dirname $BASH_SOURCE[0]`
+DOCKER_DIR="${DOCKER_DIR}/.."

 # Julia 1.6.1 + Postgres:13
 docker build --pull \
@@ -10,7 +12,7 @@ docker build --pull \
    --build-arg JULIA_MAJOR=1.6 \
    --build-arg JULIA_VERSION=1.6.1 \
    --build-arg JULIA_SHA256=7c888adec3ea42afbfed2ce756ce1164a570d50fa7506c3f2e1e2cbc49d52506 \
-   -t pljulia:pg13-jl1.6 .
+   -t pljulia:pg13-jl1.6 $DOCKER_DIR

 # Julia 1.0.5 + Postgres:12
 docker build --pull \
@@ -18,7 +20,7 @@ docker build --pull \
    --build-arg JULIA_MAJOR=1.0 \
    --build-arg JULIA_VERSION=1.0.5 \
    --build-arg JULIA_SHA256=9dedd613777ba6ebd8aee5796915ff50aa6188ea03ed143cb687fc2aefd76b03 \
-   -t pljulia:pg12-jl1.0 .
+   -t pljulia:pg12-jl1.0 $DOCKER_DIR

 # Julia 1.6.1 + postgis/postgis:13-3.1
 docker build --pull \
@@ -26,7 +28,7 @@ docker build --pull \
    --build-arg JULIA_MAJOR=1.6 \
    --build-arg JULIA_VERSION=1.6.1 \
    --build-arg JULIA_SHA256=7c888adec3ea42afbfed2ce756ce1164a570d50fa7506c3f2e1e2cbc49d52506 \
-   -t pljulia:pg13-pgis3.1-jl1.6 .
+   -t pljulia:pg13-pgis3.1-jl1.6 $DOCKER_DIR

 # List docker images
 docker images | grep pljulia
--
2.20.1

```

**Comment by ImreSamu** [comment]
> I'm wondering if this minor filename change and move looks ok for this pull request?

looks ok :)

> I have some ideas for some more extensive changes,

ok, I will wait ... ping me if you are finished .. :)

**Comment by markwkm** [comment]
Ok, I've amended your commit with my changes and pulled it into the main branch.  Thanks!

**Pull request closed without merging**
